-- evidence 표: 근거노트 한 장 = 한 행 (현재 Supabase에 적용된 상태)

-- 1) 표와 열
create table if not exists public.evidence (
  id          bigint generated by default as identity primary key,  -- 자동
  created_at  timestamptz not null default now(),                   -- 자동(저장 시각)
  item        text        not null,  -- 항목 이름 (명목)
  value       numeric     not null,  -- 값, 숫자만 (비율척도 → 계산 가능)
  unit        text        not null,  -- 단위
  source      text        not null,  -- 조문·조례번호·시행일 / 1차·2차자료
  queried_on  date        not null   -- 조회일
);

-- 2) 빈 값·짧은 출처·미래 조회일은 서버가 거부
alter table public.evidence
  add constraint evidence_item_not_blank   check (char_length(btrim(item)) > 0),
  add constraint evidence_unit_not_blank   check (char_length(btrim(unit)) > 0),
  add constraint evidence_source_min_len   check (char_length(btrim(source)) >= 5),
  add constraint evidence_queried_on_past  check (queried_on <= (now() at time zone 'Asia/Seoul')::date);

-- 3) RLS
alter table public.evidence enable row level security;

-- 읽기: 누구나 (대시보드 공개 열람)
create policy "evidence_select_public"
  on public.evidence for select to anon, authenticated using (true);

-- 쓰기: 링크를 가진 누구나 (추가만 가능 · 수정·삭제 정책은 없으므로 거부됨)
create policy "evidence_insert_public"
  on public.evidence for insert to anon, authenticated with check (true);
